# Generated by Django 4.0 on 2023-12-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoria_receita_ingrediente_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaingrediente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
