# Generated by Django 4.0 on 2023-12-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_categoriaingrediente_id_alter_ingrediente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaingrediente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
